spring.application.name=ticketflow

spring.datasource.url=jdbc:postgresql://localhost:5433/ticketflow
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.access.secret=${JWT_ACCESS_SECRETKEY}
# 15 min
jwt.access.expiration=900000

jwt.refresh.secret=${JWT_REFRESH_SECRETKEY}
# 7 days
jwt.refresh.expiration=604800000

spring.data.redis.host=localhost
spring.data.redis.port=6380

spring.profiles.active=dev